### ISSUE TITLE
add topic cnn

### ISSUE THREAD

**Issue by Beliavsky** [nedtaylor/athena#1]
I suggest adding the topic `cnn` in the About section

**Comment by nedtaylor** [comment]
Hi @Beliavsky. Thanks for the suggestion! 🙂

I have added further details to the About section. Hopefully this is now sufficient. Let me know if you feel there should be more. If not, I'll close this issue.

**Comment by Beliavsky** [comment]
What I meant was to to add the `cnn` tag along with your other tags such as `convolution` in the About section, so that a topic search of `cnn` will bring up your project.

**Comment by nedtaylor** [comment]
Awesome, thanks for clarifying @Beliavsky. I have added that and will now close this issue. If there are any more you can recommend, please do. 🙂
