### ISSUE TITLE
CONTRIBUTING.md was largely copied from neural-fortran

### ISSUE THREAD

**Issue by milancurcic** [nedtaylor/athena#23]
CONTRIBUTING.md, as of 0d3f02bef9439f8b3fd0355463fd8b0a9fe8dac9, seems copied from https://github.com/modern-fortran/neural-fortran/blob/main/CONTRIBUTING.md and only edited to change the occasional wording and to account for different features of the library. For example, the layout, sections, and sentence structures and semantics are almost exactly the same.

Personally, as creator of neural-fortran and its CONTRIBUTING.md doc, I don't mind as long as you reference it at the top (e.g. "This document was adapted from https://github.com/modern-fortran/neural-fortran/blob/main/CONTRIBUTING.md", or similar). But given that the software and its docs are part of the submission itself, which is expected to be original, this may be problematic.

This CONTRIBUTING.md is not the kind of generic CONTRIBUTING guide for community projects (in which case a copied CONTRIBUTING.md may not be a problem), but bespoke and very specific to the library.

@haozeke what's your take or is there a JOSS guideline for this? If it's problematic, a simple solution could be to simply rewrite CONTRIBUTING.md in original language.

To be clear, I don't think this was intentional but merely an honest omission by @nedtaylor.

I see similar issues with parts of the code, but I'll open separate issues for those.

Part of https://github.com/openjournals/joss-reviews/issues/6492

**Comment by nedtaylor** [comment]
You are completely correct, @milancurcic. I used the neural-fortran as a template. I definitely should have referenced your original document in the CONTRIBUTING.md file (as I had not written one before, I thought it was a good one to use as an example).

@HaoZeke, as Milan has mentioned, if the CONTRIBUTING.md needs to be clearly original, then I am happy to rewrite it and any other offending parts of the code.

@milancurcic I am sorry about that. I will include references in CONTRIBUTING.md (and other parts of the code) where clear inspiration has been taken from neural-fortran. This is why I felt it good to have you as a one of the referees to ascertain whether ATHENA is different enough to be worth being its own code or whether it should be integrated into neural-fortran.

**Comment by HaoZeke** [comment]
I would prefer to have clearer attribution than obfuscation just for JOSS. Since these are both MIT licensed codes, I think providing attribution is enough. Note that this doesn't extend to the article itself or the principal claims of the software, which should stand-alone as a scientific contribution (and will be determined separately by the reviewers).

**Comment by milancurcic** [comment]
I agree with the approach suggested by @HaoZeke.

**Comment by nedtaylor** [comment]
Thank you for the clarification here. I have now included a reference in commit 35ff066 in the `development` branch.

I will start combing through the rest of the code to provide more explicit references to neural-fortran (but as you said, that's for a the opening of a different issue).

**Comment by nedtaylor** [comment]
I have opened up an issue relating to required references neural-fortran within the code, #24. I think I have captured all parts, @milancurcic.

Further discussions relating to that topic can be handled on that thread.

**Comment by nedtaylor** [comment]
Merged into main. Closing.

Please reopen if more discussions are required regarding this.
