### ISSUE TITLE
Statement of need in the docs

### ISSUE THREAD

**Issue by milancurcic** [nedtaylor/athena#39]
Following the checklist, can you point me to, or add if not present, the statement of need to the docs (ideally near the top of the README.md):

> A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?

Part of https://github.com/openjournals/joss-reviews/issues/6492

**Comment by nedtaylor** [comment]
Would this be the same as the Statement of Need provided in the paper.md (in the `paper` branch)? If so, I'll paste that into the README.md near the top.

**Comment by milancurcic** [comment]
I don't think it needs to be but I also think it can be.

**Comment by nedtaylor** [comment]
Added in commit 0b67b82 to main branch.

Slightly modified and cutdown version of what is in the paper.
