### ISSUE TITLE
[PROPOSAL] activation layer

### ISSUE THREAD

**Issue by nedtaylor** [nedtaylor/athena#46]
### Reasoning

Activation functions are quite often applied as isolated layers (whilst still being available directly within a learnable layer such as convolutional layers).

### Prior Art

Tensorflow: https://www.tensorflow.org/api_docs/python/tf/keras/layers/Activation

**Comment by nedtaylor** [comment]
Implemented in branch [46-proposal-activation-layer](https://github.com/nedtaylor/athena/tree/46-proposal-activation-layer)

**Comment by nedtaylor** [comment]
@ofmla Following our discussion on issue #45, I have now implemented an `actv_layer_type()` that can be used to apply only activation functions. If you wish to use it, its implementation can be found in branch  ([46-proposal-activation-layer](https://github.com/nedtaylor/athena/tree/46-proposal-activation-layer)). You would add it to a network just like any others:

```
     call network%add( actv_layer_type( activation_function = "softmax" ) )
```

Its accepted arguments are `activation_function` and `activation_scale` (with the standard internal ones of `input_shape` and `batch_size` that you shouldn't have to set manually).

From my quick testing, it seems to work appropriately with forward and backward propagation on the MNIST dataset. I did have to fix `None` and `Linear` activation functions, as I realised their differentiation forms were incorrectly implemented.

If you do end up testing this branch, let me know whether you encounter any issues or if it works as expected.

**Comment by ofmla** [comment]
That was fast! Thanks a lot—I'll take a look, and if I run into any issues, I'll let you know.

**Comment by ofmla** [comment]
Well, it seems fine, but even with this addition, another layer of the `add` type (https://www.tensorflow.org/api_docs/python/tf/keras/layers/Add) might be needed to fully implement ResNet with Athena, I suppose. This link shows an implementation using TF. https://github.com/christianversloot/machine-learning-articles/blob/main/how-to-build-a-resnet-from-scratch-with-tensorflow-2-and-keras.md.

**Comment by nedtaylor** [comment]
> Well, it seems fine, but even with this addition, another layer of the `add` type (https://www.tensorflow.org/api_docs/python/tf/keras/layers/Add) might be needed to fully implement ResNet with Athena, I suppose. This link shows an implementation using TF. https://github.com/christianversloot/machine-learning-articles/blob/main/how-to-build-a-resnet-from-scratch-with-tensorflow-2-and-keras.md.

@ofmla, thanks for the links. I have had a brief look and I think that implementation of a residual layer will be more complicated. I have some ideas, but might take a few days to implement. But it is definitely something I'd like to add. I have set up a new issue for it #47, where that should be discussed in the future. I imagine One could possibly already set it up manually by just using the layer types rather than the automatic training built into the `network_type`.

> Another question: Is there a way to get the output of a layer in the network, for example, the output of a Conv2d layer? I ask this because, in the example linked, intermediate copies are needed, which are then added using the `add` layer.

Yes, each layer has the subroutine `get_output()`. This can be used like so (if we have a variable called `conv2d` with type `conv2d_layer_type`:
```
   call conv2d%get_output(output)
```

Here, `output` should be a real array of rank 1, 2, or the shape of the output. If rank 1 is provided, the entire thing is flattened, if rank 2 is provided, the dimensions are (output, batch), and if the proper rank is provided, then the output is outputted as one would expect the shape to be from the output of that a layer.

**Comment by ofmla** [comment]
Yep, I figured that the implementation might not be that simple at the moment. Still, the addition would be interesting, as ResNet, though a bit old, is still widely used, I think. Thanks!"

**Comment by nedtaylor** [comment]
Implemented in development branch.
